### PR TITLE
#74 closes

### PR DESCRIPTION
**Pull request by tonyk7440**
Resolves the created issue #74 

Ready for review, thanks!

### CODE REVIEW

**Comment by mdancho84** [comment]
Thanks for doing the PR. Much appreciated. Can you quickly show me how this resolves the error?

**Comment by tonyk7440** [comment]
Hi Matt, sure thing, see the same example as in the issue below, instead of throwing an error it is padding the column with NA values if the group has less observations than a specified lag

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(timetk)

m4_monthly %>%
    group_by(id) %>%
    tk_augment_lags(.value = contains("value"), .lags = c(1, 2, 3))
#> # A tibble: 1,574 x 6
#> # Groups:   id [4]
#>    id    date       value value_lag1 value_lag2 value_lag3
#>    <fct> <date>     <dbl>      <dbl>      <dbl>      <dbl>
#>  1 M1    1976-06-01  8000         NA         NA         NA
#>  2 M1    1976-07-01  8350       8000         NA         NA
#>  3 M1    1976-08-01  8570       8350       8000         NA
#>  4 M1    1976-09-01  7700       8570       8350       8000
#>  5 M1    1976-10-01  7080       7700       8570       8350
#>  6 M1    1976-11-01  6520       7080       7700       8570
#>  7 M1    1976-12-01  6070       6520       7080       7700
#>  8 M1    1977-01-01  6650       6070       6520       7080
#>  9 M1    1977-02-01  6830       6650       6070       6520
#> 10 M1    1977-03-01  5710       6830       6650       6070
#> # ... with 1,564 more rows

m4_monthly %>%
    group_by(id) %>%
    count() %>%
    arrange(n)
#> # A tibble: 4 x 2
#> # Groups:   id [4]
#>   id        n
#>   <fct> <int>
#> 1 M750    306
#> 2 M1000   330
#> 3 M1      469
#> 4 M2      469

m4_monthly %>%
    group_by(id) %>%
    tk_augment_lags(contains("value"), .lags = c(1, 2, 3, 310))
#> # A tibble: 1,574 x 7
#> # Groups:   id [4]
#>    id    date       value value_lag1 value_lag2 value_lag3 value_lag310
#>    <fct> <date>     <dbl>      <dbl>      <dbl>      <dbl>        <dbl>
#>  1 M1    1976-06-01  8000         NA         NA         NA           NA
#>  2 M1    1976-07-01  8350       8000         NA         NA           NA
#>  3 M1    1976-08-01  8570       8350       8000         NA           NA
#>  4 M1    1976-09-01  7700       8570       8350       8000           NA
#>  5 M1    1976-10-01  7080       7700       8570       8350           NA
#>  6 M1    1976-11-01  6520       7080       7700       8570           NA
#>  7 M1    1976-12-01  6070       6520       7080       7700           NA
#>  8 M1    1977-01-01  6650       6070       6520       7080           NA
#>  9 M1    1977-02-01  6830       6650       6070       6520           NA
#> 10 M1    1977-03-01  5710       6830       6650       6070           NA
#> # ... with 1,564 more rows
```

<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mdancho84** [comment]
Awesome - Also I have more fixes I could use your help on if you are interested in helping out more with `timetk` and `modeltime`. Let me know.

**Comment by tonyk7440** [comment]
Hi @mdancho84, I'm not sure how much time I can commit but I try to lend a hand.

Not sure how you want to approach it, if you have any ideas then feel free to let me know, otherwise I was thinking of making a few issues to get your thoughts on some enhancements

**Pull request merged**
