### PR TITLE
fix #56

### LINKED ISSUE #56: padder does not handle `.end_date` correctly
https://github.com/business-science/timetk/blob/e9a2e101d844891b012a0694668bab808b1fb4d4/R/dplyr-pad_by_time.R#L181

This branch of logic is using `.start_date` instead of `.end_date`.

### PR DESCRIPTION
**Pull request by TylerGrantSmith**
It seemed more reasonable to just refactor the parsing statements into a separate function since they do the same thing.  

This does not ultimately solve my actual original problem illustrated below, showing how padding can fail for `POSIXt` columns that cross daylight savings boundaries.

``` r
df <- tibble::tibble(date=as.POSIXct(c("2020-01-01", "2020-04-30")))
df_pad <- timetk::pad_by_time(df, date, "day")
#> Error: The specified interval is invalid for the datetime variable.
#>   Not all original observation are in the padding.
#>   If you want to pad at this interval, aggregate the data first with thicken.

# error ultimately traces to the `padr:::pad` call which calls
# padr:::span_from_min_max_single
padr:::span_from_min_max_single
#> function (start, end, interval, id_vars) 
#> {
#>     ret <- data.frame(span = seq(start, end, by = interval))
#>     return(as.data.frame(cbind(ret, id_vars)))
#> }
#> <bytecode: 0x000000001f02dd08>
#> <environment: namespace:padr>

# the problem can be understood from this excerpt of `?seq.POSIXt`
#   
#  "The difference between "day" and "DSTday" is that the former ignores changes 
#  to/from daylight savings time and the latter takes the same clock time each
#  day. "week" ignores DST (it is a period of 144 hours), but "7 DSTdays" can be 
#  used as an alternative. "month" and "year" allow for DST."

# would expect both days to appear, but daylight savings messes it up
seq(as.POSIXct("2020-03-08"),as.POSIXct("2020-03-09"), "day")
#> [1] "2020-03-08 CST"

# here we see that one "day" is 86400 seconds later, which is 1am the 
# following day
seq(as.POSIXct("2020-03-08"),as.POSIXct("2020-03-10"), "day")
#> [1] "2020-03-08 00:00:00 CST" "2020-03-09 01:00:00 CDT"

# corrected
seq(as.POSIXct("2020-03-08"),as.POSIXct("2020-03-09"), "DSTday")
#> [1] "2020-03-08 CST" "2020-03-09 CDT"
```

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

There are a number of ways this could be resolved, but I think it would require being opinionated.

### CODE REVIEW

**Comment by mdancho84** [comment]
Nice work - It looks like we should at a minimum alert `padr` since the issue source stems from the daylight savings time within the `padr:::span_from_min_max_single`

**Comment by TylerGrantSmith** [comment]
It could be worth mentioning, but as far as I can tell this would be "expected" behavior since `padr::pad` accepts for `by` "Any character string that would be accepted by `seq.Date()` or `seq.POSIXt`.", and so it should carry the same caveats of those functions.

**Comment by TylerGrantSmith** [comment]
Looking more at the `padr::pad` documentation, it explicitly mentions in the Details what the 'accepted' units should be and does not mention `"DTSday"`.  So I think I agree that in this context they should probably clarify that if you use "day" to mean precisely 24 hours, them you should use specifically "24 hours" and they should substitute `"DSTday"` for `"day"`and `"7 DSTdays"` for `"week"` before passing it to `seq`

**Comment by mdancho84** [comment]
That's a good point. 

Are you able to get the desired result if you pass `.by = "DSTday"` or is there something that needs to be done to the function to handle this situation?

**Comment by TylerGrantSmith** [comment]
No, `padr::pad` errors because it tries to convert the `by` argument to a number of seconds. but `padr:::convert_int_to_hours` breaks it because it doesn't handle `"DSTday"`.  I will write up an issue on the `padr` repo.

**Comment by TylerGrantSmith** [comment]
EdwinTh/padr#78

**Review by mdancho84 — APPROVED** [review]
Looks good

**Pull request merged**
